# Generated by Django 5.1.3 on 2024-11-23 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_diary_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsdiaries",
            name="diary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_entries",
                to="main_app.diary",
            ),
        ),
    ]
