# Generated by Django 5.1.3 on 2024-11-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0003_alter_user_height_alter_user_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
